-- 코드를 입력하세요
SELECT
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM
    BOOK B
JOIN
    AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN
    BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE
    TO_CHAR(BS.SALES_DATE, 'YYYYMM') = '202201'
GROUP BY
    B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY
    B.AUTHOR_ID, B.CATEGORY DESC