-- CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H, CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
-- C.CAR_TYPE IN ('세단', 'SUV')
-- '202211' NOT BETWEEN TO_CHAR(H.START_DATE, 'YYYYMM') AND TO_CHAR(H.END_DATE, 'YYYYMM')
-- 30 * C.DAILY_FEE * 할인 >= 500000
-- AND 30 * C.DAILY_FEE * 할인 < 2000000
-- C.CAR_ID, C.CAR_TYPE, 대여 금액(FEE)
-- ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC
SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    (100 - DP.DISCOUNT_RATE) / 100 * 30 * C.DAILY_FEE AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR C
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP ON C.CAR_TYPE = DP.CAR_TYPE AND DP.DURATION_TYPE = '30일 이상'
WHERE
    C.CAR_TYPE IN ('세단', 'SUV')
AND C.CAR_ID NOT IN (
        SELECT
            CAR_ID
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
            '202211' BETWEEN TO_CHAR(START_DATE, 'YYYYMM') AND TO_CHAR(END_DATE, 'YYYYMM')
    )
AND (100 - DP.DISCOUNT_RATE) / 100 * 30 * C.DAILY_FEE BETWEEN 500000 AND 1999999
ORDER BY
    FEE DESC, C.CAR_TYPE, C.CAR_ID DESC