-- 코드를 입력하세요
SELECT
    GU.USER_ID,
    GU.NICKNAME,
    GU.CITY || ' ' || GU.STREET_ADDRESS1 || ' ' || GU.STREET_ADDRESS2 AS "전체주소",
    REGEXP_REPLACE(GU.TLNO, '(\d{3})(\d{4})(\d{4})', '\1-\2-\3') AS "전화번호"
FROM
    USED_GOODS_BOARD GB
JOIN
    USED_GOODS_USER GU ON GB.WRITER_ID = GU.USER_ID
GROUP BY
    GU.USER_ID, 
    GU.NICKNAME, 
    GU.CITY, 
    GU.STREET_ADDRESS1, 
    GU.STREET_ADDRESS2, 
    GU.TLNO
HAVING
    COUNT(*) >= 3
ORDER BY
    GU.USER_ID DESC