-- 코드를 입력하세요
WITH JOINED_ID_MONTH AS (
    SELECT
        USER_ID
    FROM
        USER_INFO
    WHERE
        JOINED >= TO_DATE('20210101', 'YYYYMMDD')
    AND JOINED < TO_DATE('20220101', 'YYYYMMDD')
),
PURCHASED_ID_MONTH AS (
    SELECT
        DISTINCT USER_ID,
        EXTRACT(YEAR FROM CAST(SALES_DATE AS TIMESTAMP)) AS YEAR,
        EXTRACT(MONTH FROM CAST(SALES_DATE AS TIMESTAMP)) AS MONTH
    FROM
        ONLINE_SALE
)
SELECT
    P.YEAR,
    P.MONTH,
    COUNT(P.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(P.USER_ID) / (SELECT COUNT(*) FROM JOINED_ID_MONTH), 1) AS PURCHASED_RATIO
FROM
    PURCHASED_ID_MONTH P
JOIN
    JOINED_ID_MONTH J ON P.USER_ID = J.USER_ID
GROUP BY
    P.YEAR, P.MONTH
ORDER BY
    P.YEAR, P.MONTH