-- 코드를 입력하세요
SELECT
    RH.HISTORY_ID,
    (100 - NVL((
        SELECT
            DISCOUNT_RATE
        FROM
            CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE
            RH.END_DATE - RH.START_DATE + 1 >= TO_NUMBER(REGEXP_REPLACE(DURATION_TYPE, '[^0-9]', ''))
        AND CAR_TYPE = '트럭'
        ORDER BY
            DISCOUNT_RATE DESC
        FETCH FIRST 1 ROWS ONLY
    ), 0)) / 100 * (RH.END_DATE - RH.START_DATE + 1) * C.DAILY_FEE AS FEE
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
JOIN
    CAR_RENTAL_COMPANY_CAR C ON RH.CAR_ID = C.CAR_ID AND C.CAR_TYPE = '트럭'
ORDER BY
    FEE DESC, RH.HISTORY_ID DESC