-- 코드를 입력하세요
WITH HISTORY_DURATION_TABLE AS (
    SELECT
        HISTORY_ID,
        CAR_ID,
        END_DATE - START_DATE + 1 AS DURATION,
        CASE
            WHEN END_DATE - START_DATE + 1 >= 90 THEN '90일 이상'
            WHEN END_DATE - START_DATE + 1 >= 30 THEN '30일 이상'
            WHEN END_DATE - START_DATE + 1 >= 7 THEN '7일 이상'
            END AS DURATION_TYPE
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
SELECT
    H.HISTORY_ID,
    (100 - NVL(DP.DISCOUNT_RATE, 0)) / 100 * H.DURATION * C.DAILY_FEE AS FEE
FROM
    HISTORY_DURATION_TABLE H
JOIN
    CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID AND C.CAR_TYPE = '트럭'
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP ON H.DURATION_TYPE = DP.DURATION_TYPE AND DP.CAR_TYPE = '트럭'
ORDER BY
    FEE DESC, H.HISTORY_ID DESC