-- 코드를 입력하세요
WITH HOUR_TABLE AS (
    SELECT
        LEVEL - 1 AS HOUR
    FROM
        DUAL
    CONNECT BY
        LEVEL <= 24
)
SELECT
    H.HOUR,
    COUNT(O.ANIMAL_ID) AS COUNT
FROM
    HOUR_TABLE H
LEFT JOIN
    ANIMAL_OUTS O ON H.HOUR = EXTRACT(HOUR FROM CAST(O.DATETIME AS TIMESTAMP))
GROUP BY
    H.HOUR
ORDER BY
    H.HOUR