-- 코드를 입력하세요
WITH REVIEWERS_RANK AS (
    SELECT 
        MEMBER_ID,
        RANK() OVER (ORDER BY COUNT(*) DESC) AS REVIEW_RANK
    FROM 
        REST_REVIEW
    GROUP BY
        MEMBER_ID
)
SELECT
    P.MEMBER_NAME,
    R.REVIEW_TEXT,
    TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN (
    SELECT 
        RV.MEMBER_ID,
        RV.REVIEW_TEXT,
        RV.REVIEW_DATE
    FROM 
        REST_REVIEW RV
    JOIN
        REVIEWERS_RANK RK ON RV.MEMBER_ID = RK.MEMBER_ID AND RK.REVIEW_RANK = 1
) R ON P.MEMBER_ID = R.MEMBER_ID
ORDER BY
    R.REVIEW_DATE, R.REVIEW_TEXT