-- 코드를 입력하세요
WITH REVIEWERS_RANK AS (
    SELECT 
        MEMBER_ID,
        RANK() OVER (ORDER BY COUNT(*) DESC) AS REVIEWER_RANK
    FROM 
        REST_REVIEW
    GROUP BY
        MEMBER_ID
)
SELECT
    P.MEMBER_NAME,
    RV.REVIEW_TEXT,
    TO_CHAR(RV.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN 
    REVIEWERS_RANK RK ON P.MEMBER_ID = RK.MEMBER_ID AND RK.REVIEWER_RANK = 1
JOIN
    REST_REVIEW RV ON P.MEMBER_ID = RV.MEMBER_ID
ORDER BY
    RV.REVIEW_DATE, RV.REVIEW_TEXT