-- 코드를 입력하세요
SELECT 
    TO_NUMBER(TO_CHAR(ORG.START_DATE, 'MM')) AS MONTH,
    ORG.CAR_ID,
    COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY ORG
JOIN (
    SELECT
        CAR_ID
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE
        TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
    GROUP BY
        CAR_ID
    HAVING
        COUNT(*) >= 5
) IDS ON ORG.CAR_ID = IDS.CAR_ID
WHERE
    TO_CHAR(ORG.START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
GROUP BY
    TO_CHAR(ORG.START_DATE, 'MM'), ORG.CAR_ID
HAVING
    COUNT(*) > 0
ORDER BY
    MONTH, ORG.CAR_ID DESC