-- 코드를 입력하세요
SELECT
    MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM (
    SELECT
        TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH,
        CAR_ID,
        COUNT(*) OVER (PARTITION BY CAR_ID) AS RENTAL_COUNT
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
)
WHERE 
    RENTAL_COUNT >= 5
GROUP BY
    MONTH,
    CAR_ID
HAVING
    COUNT(*) > 0
ORDER BY
    MONTH, CAR_ID DESC