-- 코드를 작성해주세요
WITH MAX_SIZE_TABLE AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR
)
SELECT
    M.YEAR,
    ABS(M.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM
    ECOLI_DATA E
JOIN
    MAX_SIZE_TABLE M ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY
    YEAR, YEAR_DEV