-- 코드를 작성해주세요
WITH FISH_TYPE_RANKS AS (
    SELECT
        ID,
        FISH_TYPE,
        LENGTH,
        RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS LENGTH_RANK
    FROM
        FISH_INFO I
)
SELECT
    RK.ID,
    NI.FISH_NAME,
    RK.LENGTH
FROM
    FISH_NAME_INFO NI
JOIN
    FISH_TYPE_RANKS RK ON NI.FISH_TYPE = RK.FISH_TYPE AND RK.LENGTH_RANK = 1
ORDER BY
    RK.ID