SELECT 
    CATEGORY,
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
FROM (
    SELECT 
        CATEGORY,
        RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS PRICE_RANK,
        PRICE,
        PRODUCT_NAME
    FROM 
        FOOD_PRODUCT
    WHERE 
        CATEGORY IN ('과자', '국', '김치', '식용유')
)
WHERE
    PRICE_RANK = 1
ORDER BY
    MAX_PRICE DESC