SELECT
    A.CATEGORY,
    A.MAX_PRICE,
    A.PRODUCT_NAME
FROM (
        SELECT 
            CATEGORY,
            MAX(PRICE) OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS MAX_PRICE,
            PRODUCT_NAME
        FROM 
            FOOD_PRODUCT
) A
JOIN 
    FOOD_PRODUCT B ON A.PRODUCT_NAME = B.PRODUCT_NAME AND A.MAX_PRICE = B.PRICE
WHERE 
    A.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY
    A.MAX_PRICE DESC