-- 코드를 작성해주세요
WITH CODES AS (
    SELECT
        MAX(CASE WHEN NAME = 'Python' THEN CODE END) AS PYTHON,
        MAX(CASE WHEN NAME = 'C#' THEN CODE END) AS CSHARP,
        SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE END) AS FRONT
    FROM
        SKILLCODES
)
SELECT
    CASE
        WHEN D.SKILL_CODE & C.PYTHON AND D.SKILL_CODE & C.FRONT THEN 'A'
        WHEN D.SKILL_CODE & C.CSHARP THEN 'B'
        ELSE 'C' END AS GRADE,
    D.ID,
    D.EMAIL
FROM
    DEVELOPERS D
JOIN
    CODES C ON C.CSHARP + C.FRONT & D.SKILL_CODE
ORDER BY
    GRADE, D.ID